---
apiVersion: v1
kind: Service
metadata:
  name: assignment7
spec:
  selector:
      pod: assignment7-pod
  ports:
    - protocol: TCP
      port: 8080       # The port, the service listens on.
      targetPort: 80   # The port, the traffic is sent to on the Pod.
  type: LoadBalancer
 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: assignment7
spec:
  replicas: 5
  selector:
    matchLabels:
      pod: assignment7-pod
  template:
    metadata:
      labels:
        pod: assignment7-pod
    spec:
      containers:
        - name: assignment7
          image: boom210232/softarch-assignment:1.0.0